### ISSUE TITLE
Provide standardized icons (parent issue)

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/CoreUI#67]
Discussion began here: VEuPathDB/web-eda#1111

We have multiple versions of the same icon across the site. This creates an inconsistent experience and confusion for users. 

Proposal: CoreUI will provide a set of icons for all sites to use. Sites could use CoreUI's icons with something like `<Icon type="delete"/>`. 

## To Dos

- [ ] Decide on base set of icons (ex. mui)
- [ ] Find every icon used in the EDA. Choose either an icon from the base icon set or create a custom icon.
- [ ] Implement icons in CoreUI (add svg)
- [ ] Implement new icons in other repositories
